### ISSUE TITLE
Validation of upgrades to the original ScanNotate algorithm

### ISSUE THREAD

**Issue by Pamogar** [stefan-ainetter/SCANnotateDataset#1]
Hello @stefan-ainetter, thank you for your wonderful work in HOC-Search and the ScanNotate-dataset.

We are working on a number of improvements to the original [ScanNotate ](https://github.com/stefan-ainetter/SCANnotate) method, both in terms of time and accuracy, and we noticed that you have released ScanNotate-dataset with manual re-annotations. Regarding these re-annotations, are they only made in terms of the 6D pose of the CADs, or also the CAD retrieval step?

We want to implement a quantitative evaluation of our method, and your advice would be of great importance to us. In summary, we want to quantitatively evaluate the original ScanNotate method with and without our modifications. For this purpose, we need to select a Ground Truth (GT) and a series of metrics.

Regarding the GT, should we use ScanNotate-dataset as the GT for CAD retrieval and alignment on ScanNet? Given that the annotations have been supervised and manually re-annotated in case of outlier errors.

Additionally, we are currently using the ScanNet200 classes. Should we do the quantitative evaluation using these classes or ScanNet?

Finally, for the two different steps (retrieval and 6D pose estimation), what metrics would be adequate? Should we use the difference in rotation and translation with the GT for the 6D pose estimation? Should we use the Mean Chamfer Distance or the modified Mean Chamfer Distance (used in the HOC-Search paper) for the CAD retrieval?

Best regards,

Pau.

**Comment by stefan-ainetter** [comment]
Hi @Pamogar,

thank you very much for your interest!

In the manual re-annotation phase, we corrected both wrong poses and CAD model outliers, to ensure highest possible quality of the annotations. This means that the Scannotate Dataset should be very well suited as Ground Truth for your evaluation.

According to the class labels: In general, we use the class labels directly from the ScanNet GT. However, for CAD retrieval, we had to re-map them to ShapeNet classes. In the file [ScanNetAnnotations.py](https://github.com/stefan-ainetter/SCANnotateDataset/blob/9ec1d429e0e1cb57844213b405be03b7e7091d2b/ScanNetAnnotation.py) you can see that we provide the class label from the original ScanNet GT as `scannet_category_label`, and our category label from ShapeNet used for CAD retrieval as `category_label`. 

You can find our mapping from ScanNet to ShapeNet classes below. 

I think if you are currently using ScanNet200 classes, you need a similar class mapping to make it work with ShapeNet. In general, I do not recommend to use the scan2cad class labels, as they are often very different to the original ScanNet GT.

As evaluation metric, I believe it makes sense to use the difference in rotation, translation and scale to evaluate the alignment. For shape similarity, I think Mean Chamfer Distance (or classwise-mean Chamfer Distance) of retrieved CAD models and GT CAD models works well. In case your method also predicts the class label, it might also be interesting to evaluate the classification accuracy. Please note that these are just some general suggestions, as I do not know exatly what your method does. 

Hope this information helps. Let me know if you have additional questions.

Best,
Stefan


Here is how we mapped the class labels from ScanNet to ShapeNet:

|                ScanNet label               |                 ShapeNet label                 |
|:------------------------------------------:|:----------------------------------------------:|
|                 unannotated                |                      None                      |
|                    wall                    |                      None                      |
|                    floor                   |                      None                      |
|                   cabinet                  |                     cabinet                    |
|                     bed                    |                       bed                      |
|                    chair                   |                      chair                     |
|                    sofa                    |                      sofa                      |
|                    table                   |                      table                     |
|                    door                    |                      None                      |
|                   window                   |                      None                      |
|                  bookshelf                 |                    bookshelf                   |
|                   picture                  |                      None                      |
|                   counter                  |                      None                      |
|                   blinds                   |                      None                      |
|                    desk                    |                      table                     |
|                   shelves                  |                    bookshelf                   |
|                   curtain                  |                      None                      |
|                   dresser                  |                     cabinet                    |
|                   pillow                   |                     pillow                     |
|                   mirror                   |                      None                      |
|                  floor_mat                 |                      None                      |
|                   clothes                  |                      None                      |
|                   ceiling                  |                      None                      |
|                    book                    |                      None                      |
|                refridgerator               |                     cabinet                    |
|                 television                 |                     display                    |
|                    paper                   |                      None                      |
|                    towel                   |                      None                      |
|               shower curtain               |                      None                      |
|                     box                    | {trash bin, file cabinet, <br>cabinet, basket,...} |
|                 whiteborad                 |                     display                    |
|                   person                   |                      None                      |
|                 night stand                |         {table, cabinet, <br>file cabinet}         |
|                   toilet                   |                      chair                     |
|                    sink                    |                     bathtub                    |
|                    lamp                    |                      lamp                      |
|                   bathtub                  |                     bathtub                    |
|                     bag                    |                       bag                      |
| {otherstructure, otherfurniture, <br>otherprop} |                       Any                      |

**Comment by Pamogar** [comment]
Hi @stefan-ainetter,

Thank you for your answer. Given the high quality of the dataset, we will use it as the GT for our validation, and we were wondering how to reference this dataset correctly since it is not mentioned in HOC-Search or ScanNotate papers.

Best regards,

Pau.

**Comment by stefan-ainetter** [comment]
Hi @Pamogar,

good to hear that you plan to use our annotations. If you have additional questions, feel free to ask.

To reference the dataset, please cite the HOC-Search paper.

Best,
Stefan
