### ISSUE TITLE
Request to Update Broken Dataset Links

### ISSUE THREAD

**Issue by ArchHazel** [stefan-ainetter/SCANnotateDataset#2]
Dear authors,

I hope this message finds you well. I was trying to access the dataset provided for the SCANnotate project, but it appears that some of the dataset links are no longer working. Could you kindly update the links or provide an alternative location for the dataset?

The dataset is crucial for reproducing the results and continuing research based on your work. Any assistance in resolving this issue would be greatly appreciated.

Thank you in advance for your time and support!

Best regards,
Hazel

**Comment by stefan-ainetter** [comment]
Hi @ArchHazel,

Thank you very much for the hint. Our servers habe been temporarily down. The issue should be resolved now. Please try again to download the data with the corresponding links.

Best regards,
Stefan

**Comment by ArchHazel** [comment]
Thanks!
